{{- define "common-chart.configmap" -}}
{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "libs.names.fullname" . }}
  namespace: {{ include "libs.names.namespace" . | quote }}
  labels: {{- include "libs.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/name: {{ include "libs.names.fullname" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "libs.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- include "libs.tplvalues.render" (dict "value" .Values.configmap.configDataDict "context" $) | nindent 4 }}
{{- end }}
{{- end }}